services:
  timescaledb:
    image: timescale/timescaledb:2.22.0-pg17
    container_name: fiber-dashbord-timescaledb
    user: "999:999"
    environment:
      POSTGRES_DB: fiber_dashbord
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
    networks:
      - fiber-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fiber_dashbord"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  fiber-dashbord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber-dashbord-backend
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@timescaledb:5432/fiber_dashbord
      - RUST_LOG=info
      - HTTP_PORT=8080
      - ALLOW_EXIT_ON_PANIC=${ALLOW_EXIT_ON_PANIC}
      - FIBER_MAINNET_RPC_URL=${FIBER_MAINNET_RPC_URL}
      - FIBER_MAINNET_RPC_BEARER_TOKEN=${FIBER_MAINNET_RPC_BEARER_TOKEN}
      - FIBER_TESTNET_RPC_URL=${FIBER_TESTNET_RPC_URL}
      - FIBER_TESTNET_RPC_BEARER_TOKEN=${FIBER_TESTNET_RPC_BEARER_TOKEN}
      - CKB_MAINNET_RPC_URL=${CKB_MAINNET_RPC_URL}
      - CKB_MAINNET_RPC_BEARER_TOKEN=${CKB_MAINNET_RPC_BEARER_TOKEN}
      - CKB_TESTNET_RPC_URL=${CKB_TESTNET_RPC_URL}
      - CKB_TESTNET_RPC_BEARER_TOKEN=${CKB_TESTNET_RPC_BEARER_TOKEN}
      - MAINNET_FUNDING_CODE_HASH=${MAINNET_FUNDING_CODE_HASH}
      - TESTNET_FUNDING_CODE_HASH=${TESTNET_FUNDING_CODE_HASH}
      - MAINNET_COMMITMENT_CODE_HASH=${MAINNET_COMMITMENT_CODE_HASH}
      - TESTNET_COMMITMENT_CODE_HASH=${TESTNET_COMMITMENT_CODE_HASH}
      - SALVO_STATUS_ERROR=${SALVO_STATUS_ERROR}
    ports:
      - "8080:8080"
    networks:
      - fiber-network
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: always

volumes:
  timescaledb_data:

networks:
  fiber-network:
    driver: bridge
